version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_API_KEY=${SUPABASE_API_KEY}
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - VITE_API_BASE=${VITE_API_BASE}
    ports:
      - "3000:80"
    depends_on:
      - backend
volumes:
  db-data:
