services:
  - type: web
    name: iqandpoliticalpreference-backend
    env: python
    rootDir: .
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /ping
    healthCheckTimeout: 300
