create table if not exists payments (
    id bigint generated by default as identity primary key,
    payment_id text unique not null,
    user_id uuid,
    status text,
    amount numeric,
    currency text,
    raw jsonb not null,
    processed_at timestamptz
);
