name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - run: pip install -r backend/requirements.txt pytest jsonschema
      - run: pytest -v
      - uses: actions/setup-node@v4
        with: {node-version: '20'}
      - run: cd frontend && npm ci && npm run build
      - name: Install Playwright browsers (CI)
        working-directory: frontend
        run: npx playwright install --with-deps

      - name: Run Playwright E2E (uses root config pointing to ./e2e)
        working-directory: frontend
        run: npx playwright test --config ../playwright.config.ts

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
